version: '3'

services:
  db:
    image: postgres
  app:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8888:8000"
    depends_on:
      - db
